{% set name = "saspy" %}
{% set version = "5.10.0" %}
{% set hash_val = "ae53b02578fc5e6183e8fb3be6e43fa42da9225e9c8ce3471ece1e59b1fb2b4f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: {{ hash_val }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3
    - setuptools
    - pip
  run:
    - python >=3
    - ipython >=4
    - pygments
    - pandas

test:
  imports:
    - saspy

about:
  home: https://github.com/sassoftware/saspy
  license: Apache 2.0
  license_family: Apache
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: A Python interface module to the SAS System

extra:
  recipe-maintainers:
    - tomweber-sas
